# Site settings
author: Alma Flores
title: Exploring 
header-img: img/home-bg.png
email: flores.almalee@gmail.com
copyright_name: Alma Flores
description: > # this means to ignore newlines until "baseurl:"
  Delve into Programming
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  almalee24

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
